name: PyPI Publish

on: [push]

jobs:
  build-sdist:
    runs-on: ubuntu-latest

    concurrency:
      group: build-sdist

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: 'poetry'

    - name: build release distributions
      run: |-
        poetry install
        poetry build --format=wheel
        poetry build --format=sdist
      # poetry build --format=sdist

    - name: upload dists
      uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/
        # path: dist/*.tar.gz

        # build-wheels:
        #   name: Build wheels for ${{ matrix.os }}
        #   runs-on: ${{ matrix.runs-on }}
        #   strategy:
        #     matrix:
        #       os: [linux-intel, linux-arm, macOS-arm]
        #       include:
        #       - archs: auto
        #         platform: auto
        #       - os: linux-intel
        #         runs-on: ubuntu-latest
        #       - os: linux-arm
        #         runs-on: ubuntu-24.04-arm
        #       - os: macos-arm
        #         runs-on: macos-latest
        #         archs: auto,universal2

        #   steps:
        #   - uses: actions/checkout@v4

        #   - name: Build wheels
        #     uses: pypa/cibuildwheel@v2.23.2
        #     env:
        #       CIBW_PLATFORM: ${{ matrix.platform }}
        #       CIBW_ARCHS: ${{ matrix.archs }}

        #   - uses: actions/upload-artifact@v4
        #     with:
        #       name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        #       path: ./wheelhouse/*.whl

  pypi-publish:
    runs-on: ubuntu-latest

    concurrency:
      group: pypi-publish
      cancel-in-progress: false

    needs:
    - build-sdist
    # - build-wheels

    permissions:
      id-token: write

    steps:
    - name: Retrieve release distributions
      uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
