name: PyPI Publish

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'poetry'
    - run: poetry install
    - name: Build package
      run: poetry build
    - name: Publish to PyPI
      run: poetry publish
